sqlite3_file_path = "/home/obj/w/election_organizer.sqlite3"
admin_key = "gmVjwbAzYcgjhtHkYquUTgozqTRFCpFA@7CpevUoaJEXoA7YdLij_9oq_knRLgLyUopqq_3WWXXFsj3FFPyHirxVxoNq3cmnanVFEhT@qUbL4xnkeJNiUmbRCAnXdRvp%"
voter_registrar_url = "http://localhost:38080/all_voters"


[vote_requirements]
required_identity = "mtsac_cs_students"
election_name = "2025 Summer MTSAC College CS Dept Student Rep Election"
# allowed_proof_type = [
#     "student_id",
#     "youtube_video",
# ]


[admin]
ports = [
    "127.0.0.1:18081",
]

sockets = [
    "/tmp/voter_registrar.admin.socket",
]



[public]
ports = [
    "127.0.0.1:38081",
]

sockets = [
    "/tmp/voter_registrar_public.socket",
]
